export const englishMessages = {
  'common.back': 'Back',
  'common.productName': 'Financial Assistant',
  'common.retry': 'Retry',
  'auth.welcomeBody': 'Capture money activity quickly and understand your financial progress.',
  'auth.welcomeTrust': 'Suggested fields remain drafts until you confirm them. Backend calculations remain authoritative.',
  'auth.createAccount': 'Create account',
  'auth.signIn': 'Sign in',
  'auth.registerIntro': 'Start with a secure account for your financial workspace.',
  'auth.signInIntro': 'Use your Financial Assistant account.',
  'auth.email': 'Email',
  'auth.password': 'Password',
  'auth.showPassword': 'Show',
  'auth.hidePassword': 'Hide',
  'auth.emailInvalid': 'Enter a valid email address.',
  'auth.passwordInvalid': 'Password must contain at least 12 characters.',
  'auth.connectionError': 'Could not reach Financial Assistant. Check your connection and try again.',
  'auth.alreadyRegistered': 'Already have an account? Sign in',
  'auth.newAccount': 'New here? Create account',
  'shell.restoringSession': 'Restoring secure session',
  'shell.loadingProfile': 'Loading profile',
  'shell.profileUnavailable': 'Profile unavailable',
  'shell.profileUnavailableBody': 'Your profile could not be loaded. Try again before continuing.',
  'home.overview': 'Overview',
  'home.settings': 'Settings',
  'home.loading': 'Loading your overview',
  'home.stale': 'Some totals are still catching up. Last known values are shown.',
  'home.periodLabel': 'Dashboard period',
  'home.today': 'Today',
  'home.week': 'Week',
  'home.month': 'Month',
  'home.spent': '{period} spent',
  'home.limitRemaining': '{amount} left from this limit',
  'home.noLimit': 'No limit configured for this period',
  'home.summary': '{period} summary',
  'home.analytics': 'Analytics',
  'home.income': 'Income',
  'home.expenses': 'Expenses',
  'home.balanceChange': 'Balance change',
  'home.noActivity': 'No activity for this period yet. Add a transaction or upload a receipt to begin.',
  'home.financialScore': 'Financial score',
  'home.viewFactors': 'View factors',
  'home.outOf100': 'out of 100',
  'home.latestRecommendation': 'Latest recommendation',
  'home.viewAll': 'View all',
  'home.noRecommendations': 'No recommendations right now.',
  'home.retry': 'Retry overview',
  'home.addTransaction': 'Add transaction',
  'home.uploadReceipt': 'Upload receipt',
  'analytics.title': 'Analytics',
  'analytics.subtitle': 'Income and confirmed spending',
  'analytics.periodLabel': 'Analytics period',
  'analytics.daily': 'Daily',
  'analytics.weekly': 'Weekly',
  'analytics.monthly': 'Monthly',
  'analytics.error': 'Analytics could not be loaded. Try again.',
  'analytics.stale': 'Some analytics are still catching up. Last known values are shown.',
  'analytics.loading': 'Loading analytics',
  'analytics.summary': '{period} summary',
  'analytics.spending': 'Spending',
  'analytics.noActivity': 'No confirmed activity for this period yet. Add a transaction to build your analytics.',
  'analytics.byCategory': 'Spending by category',
  'analytics.loadingCategories': 'Loading spending categories',
  'analytics.noCategories': 'No spending categories for this period yet.',
  'analytics.retry': 'Retry analytics',
  'analytics.uncategorized': 'Uncategorized',
  'notifications.title': 'Notifications',
  'notifications.unreadCount': '{count} unread',
  'notifications.error': 'Notifications could not be loaded. Try again.',
  'notifications.readError': 'The notification could not be marked as read. Try again.',
  'notifications.loading': 'Loading notifications',
  'notifications.empty': 'No notifications yet.',
  'notifications.unread': 'Unread',
  'notifications.read': 'Read',
  'notifications.itemLabel': '{status} notification: {title}',
  'notifications.push': 'Push',
  'notifications.web': 'Web',
  'notifications.markingRead': 'Marking as read...',
  'notifications.markRead': 'Mark as read',
  'notifications.retry': 'Retry notifications',
  'permissions.camera': 'Camera',
  'permissions.gallery': 'Gallery',
  'permissions.files': 'Files',
  'permissions.cameraTitle': 'Use the camera for this receipt?',
  'permissions.galleryTitle': 'Choose a receipt from your photos?',
  'permissions.cameraRationale': 'Camera access is used only when you choose to photograph a receipt. The photo stays on this device until you choose Upload receipt.',
  'permissions.galleryRationale': 'Photo access is used only to let you select a receipt. Financial Assistant does not browse or upload other photos.',
  'permissions.continue': 'Continue',
  'permissions.notNow': 'Not now',
  'permissions.cameraDenied': 'Camera access was not granted. Use Gallery or Files instead, or enter the transaction manually.',
  'permissions.galleryDenied': 'Photo access was not granted. Use Camera or Files instead, or enter the transaction manually.',
  'permissions.tryAgain': 'Try permission again',
  'permissions.openSettings': 'Open device settings',
  'permissions.useGallery': 'Use Gallery instead',
  'permissions.useCamera': 'Use Camera instead',
  'permissions.useFiles': 'Choose from Files',
  'permissions.receiptPrivacy': 'Receipts may contain personal financial data. An image is uploaded only after you choose Upload receipt, and the resulting draft never becomes a transaction until you review and confirm it.',
  'permissions.checkFailed': 'Device permission could not be checked. Choose Files or try again.',
  'permissions.requestFailed': 'Device permission could not be requested. Choose Files or try again.',
  'permissions.settingsFailed': 'Device settings could not be opened. Open this app in system settings manually.',
  'permissions.thisDevice': 'This device',
  'permissions.notificationAllowed': 'Notification permission is allowed.',
  'permissions.notificationDenied': 'Notification permission is blocked on this device.',
  'permissions.notificationUnavailable': 'Device permission is managed outside this app.',
  'permissions.notificationNotGranted': 'Notification permission has not been granted yet.',
  'permissions.notificationMismatch': 'Push is enabled in your account, but this device cannot show it until permission is allowed.',
  'permissions.notificationRationale': 'Allow notifications only if you want the budget alerts and weekly summaries enabled in your account. You can continue using Financial Assistant without notifications.',
  'permissions.reviewNotificationAccess': 'Review notification access',
  'permissions.notificationOptional': 'Notifications are optional. If enabled, your device asks after setup; if denied, you can continue and change access later in Settings.',
  'permissions.enableNotifications': 'Enable budget alerts and weekly summaries',
} as const;

export type MessageKey = keyof typeof englishMessages;

export const ukrainianMessages: Record<MessageKey, string> = {
  'common.back': 'Назад',
  'common.productName': 'Фінансовий асистент',
  'common.retry': 'Повторити',
  'auth.welcomeBody': 'Швидко фіксуйте рух коштів і стежте за фінансовим прогресом.',
  'auth.welcomeTrust': 'Запропоновані поля залишаються чернеткою до вашого підтвердження. Розрахунки виконує сервер.',
  'auth.createAccount': 'Створити обліковий запис',
  'auth.signIn': 'Увійти',
  'auth.registerIntro': 'Почніть із захищеного облікового запису для свого фінансового простору.',
  'auth.signInIntro': 'Використайте свій обліковий запис Фінансового асистента.',
  'auth.email': 'Електронна пошта',
  'auth.password': 'Пароль',
  'auth.showPassword': 'Показати',
  'auth.hidePassword': 'Сховати',
  'auth.emailInvalid': 'Введіть коректну електронну адресу.',
  'auth.passwordInvalid': 'Пароль має містити щонайменше 12 символів.',
  'auth.connectionError': 'Не вдалося підключитися до Фінансового асистента. Перевірте з’єднання та повторіть спробу.',
  'auth.alreadyRegistered': 'Уже маєте обліковий запис? Увійти',
  'auth.newAccount': 'Ще не зареєстровані? Створити обліковий запис',
  'shell.restoringSession': 'Відновлення захищеної сесії',
  'shell.loadingProfile': 'Завантаження профілю',
  'shell.profileUnavailable': 'Профіль недоступний',
  'shell.profileUnavailableBody': 'Не вдалося завантажити профіль. Повторіть спробу перед продовженням.',
  'home.overview': 'Огляд',
  'home.settings': 'Налаштування',
  'home.loading': 'Завантаження огляду',
  'home.stale': 'Деякі підсумки ще оновлюються. Показано останні відомі значення.',
  'home.periodLabel': 'Період огляду',
  'home.today': 'Сьогодні',
  'home.week': 'Тиждень',
  'home.month': 'Місяць',
  'home.spent': 'Витрати: {period}',
  'home.limitRemaining': 'Залишок за лімітом: {amount}',
  'home.noLimit': 'Для цього періоду ліміт не налаштовано',
  'home.summary': 'Підсумок: {period}',
  'home.analytics': 'Аналітика',
  'home.income': 'Доходи',
  'home.expenses': 'Витрати',
  'home.balanceChange': 'Зміна балансу',
  'home.noActivity': 'За цей період ще немає операцій. Додайте транзакцію або завантажте чек.',
  'home.financialScore': 'Фінансова оцінка',
  'home.viewFactors': 'Переглянути фактори',
  'home.outOf100': 'зі 100',
  'home.latestRecommendation': 'Остання рекомендація',
  'home.viewAll': 'Переглянути всі',
  'home.noRecommendations': 'Наразі рекомендацій немає.',
  'home.retry': 'Оновити огляд',
  'home.addTransaction': 'Додати транзакцію',
  'home.uploadReceipt': 'Завантажити чек',
  'analytics.title': 'Аналітика',
  'analytics.subtitle': 'Доходи та підтверджені витрати',
  'analytics.periodLabel': 'Період аналітики',
  'analytics.daily': 'День',
  'analytics.weekly': 'Тиждень',
  'analytics.monthly': 'Місяць',
  'analytics.error': 'Не вдалося завантажити аналітику. Повторіть спробу.',
  'analytics.stale': 'Деякі дані аналітики ще оновлюються. Показано останні відомі значення.',
  'analytics.loading': 'Завантаження аналітики',
  'analytics.summary': 'Підсумок: {period}',
  'analytics.spending': 'Витрати',
  'analytics.noActivity': 'За цей період ще немає підтверджених операцій. Додайте транзакцію.',
  'analytics.byCategory': 'Витрати за категоріями',
  'analytics.loadingCategories': 'Завантаження категорій витрат',
  'analytics.noCategories': 'За цей період ще немає категорій витрат.',
  'analytics.retry': 'Оновити аналітику',
  'analytics.uncategorized': 'Без категорії',
  'notifications.title': 'Сповіщення',
  'notifications.unreadCount': 'Непрочитані: {count}',
  'notifications.error': 'Не вдалося завантажити сповіщення. Повторіть спробу.',
  'notifications.readError': 'Не вдалося позначити сповіщення прочитаним. Повторіть спробу.',
  'notifications.loading': 'Завантаження сповіщень',
  'notifications.empty': 'Сповіщень ще немає.',
  'notifications.unread': 'Непрочитане',
  'notifications.read': 'Прочитане',
  'notifications.itemLabel': '{status} сповіщення: {title}',
  'notifications.push': 'Push',
  'notifications.web': 'Веб',
  'notifications.markingRead': 'Позначення прочитаним...',
  'notifications.markRead': 'Позначити прочитаним',
  'notifications.retry': 'Оновити сповіщення',
  'permissions.camera': 'Камера',
  'permissions.gallery': 'Галерея',
  'permissions.files': 'Файли',
  'permissions.cameraTitle': 'Використати камеру для цього чека?',
  'permissions.galleryTitle': 'Вибрати чек серед фотографій?',
  'permissions.cameraRationale': 'Доступ до камери використовується лише коли ви фотографуєте чек. Фото залишається на пристрої, доки ви не натиснете «Завантажити чек».',
  'permissions.galleryRationale': 'Доступ до фотографій використовується лише для вибору чека. Фінансовий асистент не переглядає та не завантажує інші фото.',
  'permissions.continue': 'Продовжити',
  'permissions.notNow': 'Не зараз',
  'permissions.cameraDenied': 'Доступ до камери не надано. Скористайтеся Галереєю або Файлами чи введіть транзакцію вручну.',
  'permissions.galleryDenied': 'Доступ до фотографій не надано. Скористайтеся Камерою або Файлами чи введіть транзакцію вручну.',
  'permissions.tryAgain': 'Запитати дозвіл ще раз',
  'permissions.openSettings': 'Відкрити налаштування пристрою',
  'permissions.useGallery': 'Скористатися Галереєю',
  'permissions.useCamera': 'Скористатися Камерою',
  'permissions.useFiles': 'Вибрати з Файлів',
  'permissions.receiptPrivacy': 'Чеки можуть містити особисті фінансові дані. Зображення завантажується лише після натискання «Завантажити чек», а чернетка стане транзакцією тільки після вашої перевірки й підтвердження.',
  'permissions.checkFailed': 'Не вдалося перевірити дозвіл пристрою. Виберіть Файли або повторіть спробу.',
  'permissions.requestFailed': 'Не вдалося запитати дозвіл пристрою. Виберіть Файли або повторіть спробу.',
  'permissions.settingsFailed': 'Не вдалося відкрити налаштування пристрою. Відкрийте налаштування цієї програми вручну.',
  'permissions.thisDevice': 'Цей пристрій',
  'permissions.notificationAllowed': 'Сповіщення дозволено.',
  'permissions.notificationDenied': 'Сповіщення заблоковано на цьому пристрої.',
  'permissions.notificationUnavailable': 'Дозволом керують поза цією програмою.',
  'permissions.notificationNotGranted': 'Дозвіл на сповіщення ще не надано.',
  'permissions.notificationMismatch': 'Push-сповіщення ввімкнено в обліковому записі, але пристрій не показуватиме їх без дозволу.',
  'permissions.notificationRationale': 'Дозвольте сповіщення, лише якщо хочете отримувати бюджетні попередження та щотижневі підсумки, увімкнені у вашому обліковому записі. Програмою можна користуватися без сповіщень.',
  'permissions.reviewNotificationAccess': 'Переглянути доступ до сповіщень',
  'permissions.notificationOptional': 'Сповіщення необов’язкові. Якщо їх увімкнути, пристрій запитає дозвіл після налаштування; у разі відмови можна продовжити та змінити доступ пізніше.',
  'permissions.enableNotifications': 'Увімкнути бюджетні попередження та щотижневі підсумки',
};
