export const englishMessages = {
  'common.back': 'Back',
  'common.productName': 'Financial Assistant',
  'common.retry': 'Retry',
  'auth.welcomeBody': 'Capture money activity quickly and understand your financial progress.',
  'auth.welcomeTrust': 'Suggested fields remain drafts until you confirm them. Backend calculations remain authoritative.',
  'auth.createAccount': 'Create account',
  'auth.signIn': 'Sign in',
  'auth.registerIntro': 'Start with a secure account for your financial workspace.',
  'auth.signInIntro': 'Use your Financial Assistant account.',
  'auth.email': 'Email',
  'auth.password': 'Password',
  'auth.showPassword': 'Show',
  'auth.hidePassword': 'Hide',
  'auth.emailInvalid': 'Enter a valid email address.',
  'auth.passwordInvalid': 'Password must contain at least 12 characters.',
  'auth.connectionError': 'Could not reach Financial Assistant. Check your connection and try again.',
  'auth.alreadyRegistered': 'Already have an account? Sign in',
  'auth.newAccount': 'New here? Create account',
  'shell.restoringSession': 'Restoring secure session',
  'shell.loadingProfile': 'Loading profile',
  'shell.profileUnavailable': 'Profile unavailable',
  'shell.profileUnavailableBody': 'Your profile could not be loaded. Try again before continuing.',
  'home.overview': 'Overview',
  'home.settings': 'Settings',
  'home.loading': 'Loading your overview',
  'home.stale': 'Some totals are still catching up. Last known values are shown.',
  'home.periodLabel': 'Dashboard period',
  'home.today': 'Today',
  'home.week': 'Week',
  'home.month': 'Month',
  'home.spent': '{period} spent',
  'home.limitRemaining': '{amount} left from this limit',
  'home.noLimit': 'No limit configured for this period',
  'home.summary': '{period} summary',
  'home.analytics': 'Analytics',
  'home.income': 'Income',
  'home.expenses': 'Expenses',
  'home.balanceChange': 'Balance change',
  'home.noActivity': 'No activity for this period yet. Add a transaction or upload a receipt to begin.',
  'home.financialScore': 'Financial score',
  'home.viewFactors': 'View factors',
  'home.outOf100': 'out of 100',
  'home.latestRecommendation': 'Latest recommendation',
  'home.viewAll': 'View all',
  'home.noRecommendations': 'No recommendations right now.',
  'home.retry': 'Retry overview',
  'home.addTransaction': 'Add transaction',
  'home.uploadReceipt': 'Upload receipt',
  'analytics.title': 'Analytics',
  'analytics.subtitle': 'Income and confirmed spending',
  'analytics.periodLabel': 'Analytics period',
  'analytics.daily': 'Daily',
  'analytics.weekly': 'Weekly',
  'analytics.monthly': 'Monthly',
  'analytics.error': 'Analytics could not be loaded. Try again.',
  'analytics.stale': 'Some analytics are still catching up. Last known values are shown.',
  'analytics.loading': 'Loading analytics',
  'analytics.summary': '{period} summary',
  'analytics.spending': 'Spending',
  'analytics.noActivity': 'No confirmed activity for this period yet. Add a transaction to build your analytics.',
  'analytics.byCategory': 'Spending by category',
  'analytics.loadingCategories': 'Loading spending categories',
  'analytics.noCategories': 'No spending categories for this period yet.',
  'analytics.retry': 'Retry analytics',
  'analytics.uncategorized': 'Uncategorized',
  'notifications.title': 'Notifications',
  'notifications.unreadCount': '{count} unread',
  'notifications.error': 'Notifications could not be loaded. Try again.',
  'notifications.readError': 'The notification could not be marked as read. Try again.',
  'notifications.loading': 'Loading notifications',
  'notifications.empty': 'No notifications yet.',
  'notifications.unread': 'Unread',
  'notifications.read': 'Read',
  'notifications.itemLabel': '{status} notification: {title}',
  'notifications.push': 'Push',
  'notifications.web': 'Web',
  'notifications.markingRead': 'Marking as read...',
  'notifications.markRead': 'Mark as read',
  'notifications.retry': 'Retry notifications',
} as const;

export type MessageKey = keyof typeof englishMessages;

export const ukrainianMessages: Record<MessageKey, string> = {
  'common.back': 'Назад',
  'common.productName': 'Фінансовий асистент',
  'common.retry': 'Повторити',
  'auth.welcomeBody': 'Швидко фіксуйте рух коштів і стежте за фінансовим прогресом.',
  'auth.welcomeTrust': 'Запропоновані поля залишаються чернеткою до вашого підтвердження. Розрахунки виконує сервер.',
  'auth.createAccount': 'Створити обліковий запис',
  'auth.signIn': 'Увійти',
  'auth.registerIntro': 'Почніть із захищеного облікового запису для свого фінансового простору.',
  'auth.signInIntro': 'Використайте свій обліковий запис Фінансового асистента.',
  'auth.email': 'Електронна пошта',
  'auth.password': 'Пароль',
  'auth.showPassword': 'Показати',
  'auth.hidePassword': 'Сховати',
  'auth.emailInvalid': 'Введіть коректну електронну адресу.',
  'auth.passwordInvalid': 'Пароль має містити щонайменше 12 символів.',
  'auth.connectionError': 'Не вдалося підключитися до Фінансового асистента. Перевірте з’єднання та повторіть спробу.',
  'auth.alreadyRegistered': 'Уже маєте обліковий запис? Увійти',
  'auth.newAccount': 'Ще не зареєстровані? Створити обліковий запис',
  'shell.restoringSession': 'Відновлення захищеної сесії',
  'shell.loadingProfile': 'Завантаження профілю',
  'shell.profileUnavailable': 'Профіль недоступний',
  'shell.profileUnavailableBody': 'Не вдалося завантажити профіль. Повторіть спробу перед продовженням.',
  'home.overview': 'Огляд',
  'home.settings': 'Налаштування',
  'home.loading': 'Завантаження огляду',
  'home.stale': 'Деякі підсумки ще оновлюються. Показано останні відомі значення.',
  'home.periodLabel': 'Період огляду',
  'home.today': 'Сьогодні',
  'home.week': 'Тиждень',
  'home.month': 'Місяць',
  'home.spent': 'Витрати: {period}',
  'home.limitRemaining': 'Залишок за лімітом: {amount}',
  'home.noLimit': 'Для цього періоду ліміт не налаштовано',
  'home.summary': 'Підсумок: {period}',
  'home.analytics': 'Аналітика',
  'home.income': 'Доходи',
  'home.expenses': 'Витрати',
  'home.balanceChange': 'Зміна балансу',
  'home.noActivity': 'За цей період ще немає операцій. Додайте транзакцію або завантажте чек.',
  'home.financialScore': 'Фінансова оцінка',
  'home.viewFactors': 'Переглянути фактори',
  'home.outOf100': 'зі 100',
  'home.latestRecommendation': 'Остання рекомендація',
  'home.viewAll': 'Переглянути всі',
  'home.noRecommendations': 'Наразі рекомендацій немає.',
  'home.retry': 'Оновити огляд',
  'home.addTransaction': 'Додати транзакцію',
  'home.uploadReceipt': 'Завантажити чек',
  'analytics.title': 'Аналітика',
  'analytics.subtitle': 'Доходи та підтверджені витрати',
  'analytics.periodLabel': 'Період аналітики',
  'analytics.daily': 'День',
  'analytics.weekly': 'Тиждень',
  'analytics.monthly': 'Місяць',
  'analytics.error': 'Не вдалося завантажити аналітику. Повторіть спробу.',
  'analytics.stale': 'Деякі дані аналітики ще оновлюються. Показано останні відомі значення.',
  'analytics.loading': 'Завантаження аналітики',
  'analytics.summary': 'Підсумок: {period}',
  'analytics.spending': 'Витрати',
  'analytics.noActivity': 'За цей період ще немає підтверджених операцій. Додайте транзакцію.',
  'analytics.byCategory': 'Витрати за категоріями',
  'analytics.loadingCategories': 'Завантаження категорій витрат',
  'analytics.noCategories': 'За цей період ще немає категорій витрат.',
  'analytics.retry': 'Оновити аналітику',
  'analytics.uncategorized': 'Без категорії',
  'notifications.title': 'Сповіщення',
  'notifications.unreadCount': 'Непрочитані: {count}',
  'notifications.error': 'Не вдалося завантажити сповіщення. Повторіть спробу.',
  'notifications.readError': 'Не вдалося позначити сповіщення прочитаним. Повторіть спробу.',
  'notifications.loading': 'Завантаження сповіщень',
  'notifications.empty': 'Сповіщень ще немає.',
  'notifications.unread': 'Непрочитане',
  'notifications.read': 'Прочитане',
  'notifications.itemLabel': '{status} сповіщення: {title}',
  'notifications.push': 'Push',
  'notifications.web': 'Веб',
  'notifications.markingRead': 'Позначення прочитаним...',
  'notifications.markRead': 'Позначити прочитаним',
  'notifications.retry': 'Оновити сповіщення',
};
