<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>FinancialAssistant.Mcp.Api</RootNamespace>
    <AssemblyName>FinancialAssistant.Mcp.Api</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ModelContextProtocol.AspNetCore" Version="2.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../FinancialAssistant.Mcp.Application/FinancialAssistant.Mcp.Application.csproj" />
    <ProjectReference Include="../FinancialAssistant.Mcp.Contracts/FinancialAssistant.Mcp.Contracts.csproj" />
    <ProjectReference Include="../FinancialAssistant.Mcp.Infrastructure/FinancialAssistant.Mcp.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../../shared/observability/FinancialAssistant.Shared.Observability/FinancialAssistant.Shared.Observability.csproj" />
  </ItemGroup>
</Project>
