<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>FinancialAssistant.Analytics.Domain</RootNamespace>
    <AssemblyName>FinancialAssistant.Analytics.Domain</AssemblyName>
  </PropertyGroup>
</Project>
