<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>FinancialAssistant.Expense.Api</RootNamespace>
    <AssemblyName>FinancialAssistant.Expense.Api</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.28" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../FinancialAssistant.Expense.Application/FinancialAssistant.Expense.Application.csproj" />
    <ProjectReference Include="../FinancialAssistant.Expense.Contracts/FinancialAssistant.Expense.Contracts.csproj" />
    <ProjectReference Include="../FinancialAssistant.Expense.Infrastructure/FinancialAssistant.Expense.Infrastructure.csproj" />
  </ItemGroup>
</Project>
