<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <RootNamespace>FinancialAssistant.Shared.Testing</RootNamespace>
    <AssemblyName>FinancialAssistant.Shared.Testing</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Testcontainers.Elasticsearch" Version="4.13.0" />
    <PackageReference Include="Testcontainers.Minio" Version="4.13.0" />
    <PackageReference Include="Testcontainers.RabbitMq" Version="4.13.0" />
    <PackageReference Include="Testcontainers.Redis" Version="4.13.0" />
  </ItemGroup>
</Project>
