<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>FinancialAssistant.FinancialSummary.Infrastructure</RootNamespace>
    <AssemblyName>FinancialAssistant.FinancialSummary.Infrastructure</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../FinancialAssistant.FinancialSummary.Application/FinancialAssistant.FinancialSummary.Application.csproj" />
    <ProjectReference Include="../FinancialAssistant.FinancialSummary.Domain/FinancialAssistant.FinancialSummary.Domain.csproj" />
  </ItemGroup>
</Project>
